### PR TITLE
Use JRendererJlayout in plugins

### PR DESCRIPTION
**Pull request by wilsonge**

### CODE REVIEW

**Comment by phproberto** [comment]
One of the things I found useful while working with this is to create a different function to get the layout data. This is better because:
- You can inherit parent class layout data (incredibly easy to create new fields)
- Most times you only need to change the layout data, not the rendering. So this would save us a lot of code.

Example for base field:

``` php
/**
 * Get the data that is going to be passed to the layout
 *
 * @return  array
 */
protected function getLayoutData()
{
    return array(
        'autofocus' => $this->autofocus,
        'class'     => $this->class,
        'disabled'  => $this->disabled,
        'element'   => $this->element,
        'field'     => $this,
        'id'        => $this->id,
        'multiple'  => $this->multiple,
        'name'      => $this->name,
        'readonly'  => $this->readonly,
        'required'  => $this->required,
        'size'      => $this->size,
        'value'     => $this->value
    );
}
```

Example override in child field:

``` php
/**
 * Get the data that is going to be passed to the layout
 *
 * @return  array
 */
protected function getLayoutData()
{
    $baseData = parent::getLayoutData();

    $htmlType = !empty($this->element['html_type']) ? $this->element['html_type'] : 'text';

    $extraData = array(
        'type'                => $htmlType,
        'attributes'          => $this->element->attributes(),
        'forbiddenAttributes' => $this->forbiddenAttributes
    );

    return array_merge($baseData, $extraData);
}
```

Another good example is the current `view.html.php` files where the display method contains everything. If we use the `getLayoutData()` function most views will only change that function which simplifies everything a lot.

**Comment by wilsonge** [comment]
I agree. But that would be for form fields. For plugins (for example) that wouldn't be needed as we just have one view. people aren't gonna be overriding the inputs

**Comment by phproberto** [comment]
Don't you extend JPlugin class in your own plugins?

This would allow you to:
- Use a different renderer without dealing with the data.
- Use/extend data without dealing with the renderer

If I'm right most plugins will only have the getLayoutData method. So you
can override the renderer in a base plugin class and use the same renderer
in all your plugins for example.

**Comment by wilsonge** [comment]
OK so your saying that you have a common plugin class

``` php
commonPlugin extends JPlugin
{
   abstract public function getLayoutData

  public function getRenderer($path)
  {
      new JLayoutFile($path);
  }
}
```

and a specific plugin from there with just the getLayoutData function in?

``` php
Myrealplugin extends commonPlugin
{
// plugin code here with overrides as necessary.
}
```

**Comment by phproberto** [comment]
I'm better explaining things with code :octocat: 

https://github.com/wilsonge/cms-naked/pull/1

**Comment by phproberto** [comment]
New PR with quickicons cleanup https://github.com/wilsonge/cms-naked/pull/2

**Comment by phproberto** [comment]
After that I think we have to merge this to start using the renderer on the other sections (fields, libraries, modules, etc.).

**Pull request merged**
