### PR TITLE
Layout for Field Repeatable 

### PR DESCRIPTION
**Pull request by Fedik**
Layout for Field Repeatable 
#38

with addittional changes from [[#33392] Repeatable form fields fix (2)](https://github.com/joomla/joomla-cms/pull/3574)

### CODE REVIEW

**Comment by wilsonge** [comment]
It's really not even really worth doing this until we get repeatable form fields working :( they're so broke it's unreal. tempted to go back to the functioning mootools version

**Comment by Fedik** [comment]
@wilsonge this pull includes a fixes for this field

**Comment by Fedik** [comment]
hm, something went wrong after merging the main fix :no_good:
I need update this....

**Comment by Fedik** [comment]
I made new pull request for this https://github.com/joomla/joomla-cms/pull/6917

**Pull request closed without merging**
