### PR TITLE
Updated content vote plugin to use standard plugin template overrides

### PR DESCRIPTION
**Pull request by corywebb**

### CODE REVIEW

**Comment by corywebb** [comment]
Added more commits for the following:
- Updated content pagebreak plugin to use standard template overrides
- Removed pagebreak layouts because they are no longer needed now that we are using standard template overrides
- Updated quickicon plugins to use JLayoutFile instead of getRenderer because getRenderer is not necessary
- Removed getRenderer from JPlugin because it is unnecessary

**Comment by wilsonge** [comment]
Hi,
First of all - thanks for the hard work you've clearly put into this. It's really appreciated!

Unfortunately part of the idea Roberto and myself have with this project is to "deprecate" the `getLayoutPath` function and move things across to use JLayouts as much as we can as they are much more generic and reusable. They are also more in line with the php approach that things like twig and moustache have taken in recent years.

To give you an idea of where we are looking to take this project much longer term (think Joomla 4 or 5) our goal is to move as much template overrideable views as possible to use JLayouts (including components and modules) however obviously for b/c reasons this isn't possible at the moment. However for now any plugins for example that don't already have template overrides that should do we want to move to JLayouts rather than the standard template overrides.

Again though thanks for the work you've put in. And hopefully this gives you a bit better idea of where we are looking to go in this repo.

**Comment by corywebb** [comment]
Thanks, @wilsonge 

I get that. I'm not sure if I agree, but I get it.

Can you take a look at the other commits in this pull request? I pushed them to my repo, and they got added to this pull request after the fact. I removed the use of the `getRenderer` function from the `JPlugin` class because it is unnecessary.

**Comment by wilsonge** [comment]
If you don't agree with it feel free to state your reservations :) It's still very early days and it's always good in case you think of something that hadn't occured to us!

With the getRenderer, when I release new MVC proposals in the next couple of weeks you'll see it ties up with some of the code I've written in there. However as it is, you're right it's not optimal. See this https://github.com/joomla-projects/cms-naked/pull/57 for an idea of how I see it working. Then the JRendererJlayout class can plug into modules, components or plugins.

**Comment by corywebb** [comment]
My only concern regarding moving everything in plugins over to the new JLayout paradigm is that it breaks how frontend (template) developers override layouts from plugins. The existing paradigm that people are used to is to look for the template file in _plugins/TYPE_NAME/PLUGIN_NAME/tmpl/_ and override it in _templates/TEMPLATE_NAME/html/plg_TYPE_NAME/_.

Is the long-term goal to move everything (including module and component layout files) into the new JLayout paradigm?

I still don't understand the new for all of the getRenderer complexity, even in #57 that you linked to. Doesn't `$layout = new JLayoutFile('path.to.layout.file')` do basically the same thing?

**Comment by wilsonge** [comment]
Plugins were only overridable from 3.x only. We're not gonna remove support for any using the existing paradigm either. However any that aren't we will be looking to use the 'new' method of JLayouts.

Yes indeed it's a long term goal. But as I said it will probably be Joomla 4 or maybe 5 before that can happen.

OK so the advantage being is that actually it doesn't have to be a JLayout. So it really could be twig or moustache powering your site rather than a JLayout.

**Comment by corywebb** [comment]
Ok, so you are trying to abstract out the JLayout so that the template engine used is arbitrary. I get it. Thanks for enlightening me.

**Comment by Bakual** [comment]
JLayouts should actually be more intuitive to override than our current template overrides. Because you will be able to copy the exact path to the template and don't have to adjust the folder structure.
Also there is a PR which will show the used JLayout when you enable debugging (did we already merge that one, don't remember).

**Comment by betweenbrain** [comment]
Should this PR be closed then?

**Comment by betweenbrain** [comment]
Not that I don't appreciate your efforts @corywebb!

**Comment by corywebb** [comment]
Yes, this should probably be closed.

**Pull request closed without merging**
